#!/bin/bash
set -exo pipefail

test -e lut.png || ./generate-lut

f=$(date +'%Y-%m-%d-%H%M').jpg

wget -nv https://services.swpc.noaa.gov/images/animations/ovation/north/latest.jpg -O $f
./rectilinearize $f
./mark-locations $f-rect.jpg
