#!/bin/bash
set -eo pipefail
d=$(date +'%Y-%m-%d-%H%M')
mkdir $d
cd $d
curl -s https://services.swpc.noaa.gov/images/animations/ovation/north/ | sed -nre '
	/href="aurora/ {
		s#<a href="#https://services.swpc.noaa.gov/images/animations/ovation/north/#
		s#".*##
		p
	}
' | wget -nv -i -
